# Task : Session 1
Solve these questions own your own and try to test yourself what you have learned in the session.

Happy Learning!

### Q1 :- Print the given strings as per stated format.

**Given strings**:
```
"Data" "Science" "Mentorship" "Program"
"By" "CampusX"
```
**Output**:
```
Data-Science-Mentorship-Program-started-By-CampusX
```

Concept- [Seperator and End]

In [ ]:
data = ["Data","Science","Mentorship","Program","started","By","CampusX"]
for i in range(len(data)):
  print(data[i],end='-')

Data-Science-Mentorship-Program-started-By-CampusX-

### Q2:- Write a program that will convert celsius value to fahrenheit.

In [ ]:
deg_celsius = int(input("enter the degree in celsius: "))
deg_fehrenheit = (deg_celsius*1.8)+32
print("The degree in fehrenheit: ",deg_fehrenheit)

enter the degree in celsius: 37
The degree in fehrenheit:  98.60000000000001

### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax.

In [ ]:
value1 = input("Enter the number 1: ")
value2 = input("Enter the number 2: ")
value1,value2 = value2,value1
print("Number 1: ",value1,"Number 2: ",value2)

Enter the number 1: 55
Enter the number 2: 66
Number 1:  66 Number 2:  55

### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input.

In [ ]:
import math
x1 = int(input("enter the value of x1: "))
x2 = int(input("enter the value of x2: "))
y1 = int(input("enter the value of y1: "))
y2 = int(input("enter the value of y2: "))
ed = math.sqrt((x2-x1)**2+(y2-y1)**2)
print("the equlidean distance between two points i.e x1,y1 and x2,y2 is : ",ed)

enter the value of x1: 2
enter the value of x2: -5
enter the value of y1: 1
enter the value of y2: -3
the equlidean distance between two points i.e x1,y1 and x2,y2 is :  8.06225774829855

### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user.

In [ ]:
p = int(input("enter the principle : "))
t = float(input("enter the time : "))
r = float(input("enter the rate of interest : "))

si = (p*t*r)/100
print("Simple interest is : ",si)

enter the principle : 1000
enter the time : 5
enter the rate of interest : 5
Simple interest is :  250.0

### Q6:- Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

For example:
Input:
heads -> 4
legs -> 12
<br>
Output:
dogs -> 2
chicken -> 2

In [2]:
heads = int(input("Enter the number of heads : "))
legs = int(input("Enter the number of legs : "))
calculate_head = heads/2
calculate_legs = legs/6
print("the dogs :",calculate_head,"the chickens :",calculate_legs)

Enter the number of heads : 4
Enter the number of legs : 12
the dogs : 2.0 the chickens : 2.0

### Q7:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user.

In [5]:
n = int(input("enter the number: "))
square_num = (n*(n+1)*((2*n)+1))/6
print("The sum of sqaures of ",n,"natural numbers :",square_num)

enter the number: 5
The sum of sqaures of  5 natural numbers : 55.0

### Q8:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user.

In [13]:
#an = a + (n - 1) * (b - a)

n = int(input("enter the number : "))
a = int(input("enter the first term of arithmetic series: "))
b = int(input("enter the second term of arithmetic series: "))

nth_term = a + ((n-1) * (b-a))

print("Nth term is :",nth_term)

enter the number : 5
enter the first term of arithmetic series: 2
enter the second term of arithmetic series: 6
Nth term is : 18

### Q9:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user.

In [11]:
numerator1 = int(input("enter the numerator 1: "))
numerator2 = int(input("enter the numerator 2: "))

denominator1 = int(input("enter the denominator 1: "))
denominator2 = int(input("enter the denominator 2: "))

total = ((numerator1*denominator2)/(denominator1*denominator2))+((numerator2*denominator1)/(denominator2*denominator1))
print("the sum of two fraction in decimal :",total)
num=total*(denominator1*denominator2)
deno=denominator1*denominator2
print("The sum of two fractions in fraction form :",num,"/",deno)

enter the numerator 1: 6
enter the numerator 2: 13
enter the denominator 1: 9
enter the denominator 2: 17
the sum of two fraction in decimal : 1.4313725490196076
The sum of two fractions in fraction form : 218.99999999999997 / 153

### Q10:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.



Input:<br>
Dimensions of the milk tank<br>
H = 20cm, L = 20cm, B = 20cm
<br><br>
Dimensions of the glass<br>
h = 3cm, r = 1cm

In [12]:
from math import *
l_tank = int(input("enter the length of tank: "))
b_tank = int(input("enter the bredth of tank: "))
h_tank = int(input("enter the height of tank: "))
vol_tank = l_tank*b_tank*h_tank

print(vol_tank)

h_glass = int(input("enter the height of glass: "))
r_glass = int(input("enter the radius of glass: "))
vol_glass = pi*r_glass*r_glass*h_glass

print(vol_glass)

n_glass_tank = vol_tank/vol_glass

print("the number of glasses of milk that can be obtained from tank :",n_glass_tank)

enter the length of tank: 20
enter the bredth of tank: 20
enter the height of tank: 20
8000
enter the height of glass: 3
enter the radius of glass: 1
9.42477796076938
the number of glasses of milk that can be obtained from tank : 848.8263631567752